SUBDIRS := nibbles nibbles-levels nibbles-server nibbles-gtk

all-recurse-nibbles-levels all-recurse-nibbles-server \
		all-recurse-nibbles-gtk: \
	all-recurse-nibbles

test-recurse-nibbles-levels test-recurse-nibbles-server \
		test-recurse-nibbles-gtk: \
	test-recurse-nibbles

