BIN := nibbles-gtk
THIS_CXXFLAGS := `pkg-config --cflags libglademm-2.4`
THIS_LDFLAGS := -no-install
LIBS := `pkg-config --libs libglademm-2.4` -lboost_filesystem -lboost_thread
LIB_DEP_NAMES := nibbles-client

